import { EducationalArticle, Hotspot, SymptomConcern } from "@/types";

export const educationalArticles: EducationalArticle[] = [
  {
    id: "understanding-tooth-anatomy",
    slug: "understanding-tooth-anatomy",
    category: "basics",
    title: "Understanding Tooth Anatomy: What Lies Beneath the Surface",
    summary: "Explore the biological layers of a natural tooth—from the ultra-hard enamel shell to the living pulp nerve chamber deep inside.",
    content: "A tooth is a complex living structure comprising distinct specialized tissues. The outer visible crown is protected by enamel, the hardest mineralized substance in the human body. Beneath enamel lies dentin, a softer microtubular layer that transmits thermal signals to the inner pulp. At the core is the dental pulp chamber, housing living nerves and blood vessels that nourish the tooth during development.",
    keyPoints: [
      "Enamel has no living cells and cannot regenerate on its own once worn away.",
      "Dentin contains thousands of microscopic tubules leading directly to the nerve.",
      "The dental pulp provides vital sensations and keeps the tooth nourished.",
      "The periodontal ligament anchors the tooth root firmly to the jawbone.",
    ],
    whatToDo: [
      "Protect enamel by brushing twice daily with fluoride toothpaste.",
      "Avoid using teeth as tools or crunching hard objects.",
      "Limit frequent consumption of acidic beverages and sticky sugars.",
    ],
    whenToSeeDentist: "If you experience sharp pain, visible chips, or sensitivity that lingers longer than a few seconds after eating hot or cold foods.",
    relatedTreatmentSlug: "preventive-examination",
    interactiveModelType: "anatomy",
    reviewStatus: "draft",
    seoTitle: "Understanding Tooth Anatomy | NeoDental Learn",
    seoDescription: "Learn about the layers of a tooth: enamel, dentin, pulp, and roots with interactive 3D visualizations from NeoDental Clinic.",
  },
  {
    id: "how-tooth-decay-develops",
    slug: "how-tooth-decay-develops",
    category: "problems",
    title: "How Tooth Decay Progresses: From Enamel Lesion to Cavity",
    summary: "Discover how oral bacteria and dietary sugars interact to produce acids that demineralize enamel and how early intervention saves teeth.",
    content: "Dental caries (tooth decay) is a progressive biological process. Plaque biofilm bacteria ferment carbohydrates from food, producing lactic acid that dissolves calcium and phosphate minerals from enamel. If untreated in its initial microscopic stage, the demineralization penetrates through enamel into dentin, accelerating rapidly and eventually threatening the pulp nerve.",
    keyPoints: [
      "Stage 1 (Enamel demineralization) can often be remineralized with fluoride and good hygiene.",
      "Stage 2 (Dentin decay) requires a protective restorative filling to halt bacteria.",
      "Stage 3 (Pulp infection) typically necessitates root canal therapy to save the tooth.",
    ],
    whatToDo: [
      "Maintain thorough daily plaque removal with gentle brushing and flossing.",
      "Drink water frequently to support salivary buffering capacity.",
      "Schedule routine 6-month checks for early detection before pain starts.",
    ],
    whenToSeeDentist: "At the first sign of a dark spot, chalky white patch, food trapping, or tooth sensitivity.",
    relatedTreatmentSlug: "restorative-fillings",
    interactiveModelType: "decay",
    reviewStatus: "draft",
    seoTitle: "How Tooth Decay Develops & How to Stop It | NeoDental Learn",
    seoDescription: "Step-by-step educational guide on tooth decay progression and restorative dental solutions at NeoDental Clinic.",
  },
  {
    id: "tooth-sensitivity-causes-relief",
    slug: "tooth-sensitivity-causes-relief",
    category: "problems",
    title: "Tooth Sensitivity: Why Cold and Sweet Triggers Pain",
    summary: "Understand dentin hypersensitivity, gum recession, and enamel thinning, and discover how modern dentistry provides lasting comfort.",
    content: "Dentin hypersensitivity occurs when protective enamel wears thin or gums recede, exposing the underlying dentin. Dentin is permeated with thousands of microscopic fluid-filled tubules. Cold, hot, or sweet stimuli cause rapid fluid shifts within these tubules, stimulating nerve fibers at the pulp edge and producing a sharp, fleeting sensation.",
    keyPoints: [
      "Aggressive horizontal brushing can wear down enamel near the gumline.",
      "Gum recession leaves root dentin unprotected by enamel.",
      "Desensitizing toothpastes work by blocking tubular pathways or soothing nerve endings.",
    ],
    whatToDo: [
      "Use an ultra-soft or soft toothbrush and brush in gentle circular motions.",
      "Apply desensitizing fluoride toothpaste regularly.",
      "Avoid frequent consumption of acidic citrus juices or carbonated sodas.",
    ],
    whenToSeeDentist: "If sensitivity becomes lingering, throbbing, or focused on a single tooth rather than generalized.",
    relatedTreatmentSlug: "restorative-fillings",
    interactiveModelType: "anatomy",
    reviewStatus: "draft",
    seoTitle: "Tooth Sensitivity Causes and Solutions | NeoDental Learn",
    seoDescription: "Learn why teeth become sensitive to cold and sweets, and how professional dental care protects exposed dentin.",
  },
  {
    id: "gum-health-and-bleeding-gums",
    slug: "gum-health-and-bleeding-gums",
    category: "problems",
    title: "Gum Health: Why Healthy Gums Don't Bleed",
    summary: "Learn the crucial distinction between early gingivitis and advanced periodontitis, and why healthy gums are essential for tooth stability.",
    content: "Bleeding when brushing or flossing is the most common early sign of gingivitis—inflammation of the gums caused by bacterial plaque accumulation along the gumline. If ignored, gingivitis can evolve into periodontitis, where bacterial toxins destroy the supporting periodontal ligament and bone, causing teeth to become loose.",
    keyPoints: [
      "Gingivitis is fully reversible with professional cleaning and diligent oral hygiene.",
      "Healthy gums should be firm, pale pink, and should not bleed during gentle brushing.",
      "Periodontitis is a leading cause of adult tooth loss worldwide.",
    ],
    whatToDo: [
      "Brush twice daily along the 45-degree angle where tooth meets gum.",
      "Clean between teeth daily with dental floss or interdental brushes.",
      "Receive professional scaling and polishing to remove hardened calculus.",
    ],
    whenToSeeDentist: "If your gums bleed persistently, appear red or swollen, or if you notice receding gums or loose teeth.",
    relatedTreatmentSlug: "preventive-examination",
    interactiveModelType: "anatomy",
    reviewStatus: "draft",
    seoTitle: "Gum Health & Bleeding Gums Explained | NeoDental Learn",
    seoDescription: "Discover how to prevent gum disease, reverse gingivitis, and maintain healthy periodontal tissues at NeoDental Clinic.",
  },
  {
    id: "understanding-root-canal-therapy",
    slug: "understanding-root-canal-therapy",
    category: "treatments",
    title: "Demystifying Root Canal Therapy: Saving Your Natural Tooth",
    summary: "A step-by-step breakdown of how endodontic therapy clears deep infection, relieves severe pain, and prevents tooth extraction.",
    content: "Root canal therapy is one of the most effective procedures in modern dentistry for preserving a natural tooth that would otherwise need extraction. By carefully removing infected pulp tissue, disinfecting the internal root canals, and sealing them with biocompatible materials, the procedure restores health to the surrounding jawbone and relieves pain.",
    keyPoints: [
      "The procedure eliminates infection rather than causing pain.",
      "Saving your natural tooth maintains proper chewing mechanics and prevents neighboring teeth from tilting.",
      "A crown is typically recommended afterwards to protect the treated tooth from fracture.",
    ],
    whatToDo: [
      "Follow your dentist's post-operative instructions carefully.",
      "Avoid chewing very hard foods on the treated tooth until the final crown is placed.",
      "Continue diligent brushing and flossing around the restored tooth.",
    ],
    whenToSeeDentist: "Immediately if experiencing throbbing tooth pain, sensitivity that lingers, or swelling along the jaw.",
    relatedTreatmentSlug: "root-canal-treatment",
    interactiveModelType: "root-canal",
    reviewStatus: "draft",
    seoTitle: "Root Canal Therapy Explained | NeoDental Learn",
    seoDescription: "Comprehensive educational breakdown of root canal procedures, benefits, and aftercare from NeoDental Clinic.",
  },
  {
    id: "daily-oral-hygiene-guide",
    slug: "daily-oral-hygiene-guide",
    category: "prevention",
    title: "The Essential Guide to Daily Oral Hygiene & Plaque Control",
    summary: "Simple, science-backed habits for effective tooth brushing, flossing, and dietary choices that protect your smile for a lifetime.",
    content: "Daily plaque control is the single most powerful defense against both cavities and periodontal disease. Plaque is a sticky, colorless film of bacteria that constantly forms on teeth. When left undisturbed for more than 24-48 hours, plaque hardens into calculus (tartar), which can only be removed with professional dental instruments.",
    keyPoints: [
      "Brush for a full two minutes twice daily using a soft-bristled brush.",
      "Spit out excess toothpaste after brushing, but avoid rinsing immediately with water to allow fluoride contact.",
      "Floss once daily to clean the 35-40% of tooth surfaces between teeth.",
    ],
    whatToDo: [
      "Replace your toothbrush every 3 months or sooner if bristles are frayed.",
      "Clean your tongue gently with your toothbrush to reduce oral bacteria.",
      "Stay hydrated to maintain adequate protective saliva flow.",
    ],
    whenToSeeDentist: "Every 6 months for a professional cleaning and examination.",
    relatedTreatmentSlug: "preventive-examination",
    interactiveModelType: "anatomy",
    reviewStatus: "draft",
    seoTitle: "Daily Oral Hygiene & Tooth Brushing Guide | NeoDental Learn",
    seoDescription: "Science-backed daily oral hygiene recommendations, proper brushing techniques, and flossing tips from NeoDental.",
  },
];

export const symptomConcerns: SymptomConcern[] = [
  {
    id: "tooth-pain",
    title: "Tooth Pain",
    iconName: "Activity",
    possibleMeaning: "Sharp, dull, or throbbing pain can stem from dental decay, pulp inflammation, a cracked tooth, or infection.",
    whyExaminationMatters: "Pain is a warning sign that the tooth nerve is reacting to pressure or bacterial intrusion. Clinical exam identifies the exact source.",
    treatmentApproach: "Depending on vitality: protective restoration, root canal therapy, or targeted relief.",
    whenToSeekCare: "Immediately if pain is throbbing, disrupts sleep, or is accompanied by swelling.",
    suggestedTreatmentSlug: "emergency-pain-relief",
  },
  {
    id: "tooth-sensitivity",
    title: "Tooth Sensitivity",
    iconName: "Zap",
    possibleMeaning: "Brief sharp twinges to cold, hot, or sweet foods often indicate exposed root dentin, enamel wear, or minor micro-leakage.",
    whyExaminationMatters: "Distinguishes between harmless dentin sensitivity and progressive pulp inflammation.",
    treatmentApproach: "Desensitizing agents, composite bonding, fluoride treatments, or restorative care.",
    whenToSeekCare: "If sensitivity lingers for more than a few seconds or becomes increasingly severe.",
    suggestedTreatmentSlug: "restorative-fillings",
  },
  {
    id: "bleeding-gums",
    title: "Bleeding Gums",
    iconName: "Droplet",
    possibleMeaning: "Bleeding during brushing or flossing is the hallmark of gingivitis or localized gum inflammation caused by plaque buildup.",
    whyExaminationMatters: "Early gingivitis can be completely reversed before it progresses into bone-damaging periodontitis.",
    treatmentApproach: "Professional ultrasonic scaling, deep cleaning, and customized home hygiene regimen.",
    whenToSeekCare: "If gums bleed frequently, feel tender, or appear swollen and bright red.",
    suggestedTreatmentSlug: "preventive-examination",
  },
  {
    id: "missing-tooth",
    title: "Missing Tooth",
    iconName: "CircleDot",
    possibleMeaning: "Tooth loss affects chewing efficiency, causes adjacent teeth to drift, and leads to gradual jawbone resorption.",
    whyExaminationMatters: "Evaluating remaining bone and bite alignment ensures the best replacement plan.",
    treatmentApproach: "Dental implants, fixed crowns & bridges, or custom removable appliances.",
    whenToSeekCare: "As soon as possible to prevent adjacent teeth from shifting into the gap.",
    suggestedTreatmentSlug: "dental-implants",
  },
  {
    id: "damaged-broken-tooth",
    title: "Damaged / Broken Tooth",
    iconName: "Scissors",
    possibleMeaning: "Chips, cracks, or fractures can compromise tooth strength and allow bacteria direct access to the nerve.",
    whyExaminationMatters: "Early stabilization prevents crack propagation down the root, which would require extraction.",
    treatmentApproach: "Composite bonding, partial coverage restorations, or custom-fitted crowns.",
    whenToSeekCare: "Promptly to protect exposed dentin and prevent tongue irritation from sharp edges.",
    suggestedTreatmentSlug: "dental-crowns",
  },
  {
    id: "discolored-teeth",
    title: "Discolored Teeth",
    iconName: "Sun",
    possibleMeaning: "Staining can be extrinsic (coffee, tea, spices) or intrinsic (deep enamel changes, trauma, old fillings).",
    whyExaminationMatters: "Identifies whether discoloration is surface-level or reflects an internal pulp issue.",
    treatmentApproach: "Professional polishing, aesthetic restorative bonding, or veneers.",
    whenToSeekCare: "Whenever you wish to improve the brightness and symmetry of your smile.",
    suggestedTreatmentSlug: "cosmetic-dentistry-veneers",
  },
  {
    id: "crooked-misaligned-teeth",
    title: "Crooked / Crowded Teeth",
    iconName: "Grid",
    possibleMeaning: "Crowding or misaligned dental arches make oral hygiene challenging and create uneven biting forces.",
    whyExaminationMatters: "Assessing occlusion prevents premature tooth wear, joint strain, and hidden decay.",
    treatmentApproach: "Orthodontic assessment and tailored teeth alignment roadmaps.",
    whenToSeekCare: "Anytime you wish to improve dental function, ease of cleaning, or facial aesthetics.",
    suggestedTreatmentSlug: "orthodontic-assessment",
  },
  {
    id: "swelling-gum-bump",
    title: "Swelling or Gum Bump",
    iconName: "AlertTriangle",
    possibleMeaning: "A visible bump or facial swelling indicates localized infection seeking an exit drainage pathway.",
    whyExaminationMatters: "Dental infections do not resolve on their own and require immediate professional treatment.",
    treatmentApproach: "Drainage, targeted antibiotic therapy if indicated, and root canal or extraction.",
    whenToSeekCare: "Urgent: seek care same-day to prevent spread into facial tissue spaces.",
    suggestedTreatmentSlug: "emergency-pain-relief",
  },
  {
    id: "dental-anxiety",
    title: "Dental Anxiety & Fear",
    iconName: "Smile",
    possibleMeaning: "Fear of dental visits is common and can cause patients to delay necessary care until problems become acute.",
    whyExaminationMatters: "Understanding that modern dental care is gentle and controlled puts patients at ease.",
    treatmentApproach: "Gentle step-by-step pacing, transparent explanations, and comfortable local anesthesia.",
    whenToSeekCare: "Schedule a low-stress consultation to meet the team and discuss your comfort preferences.",
    suggestedTreatmentSlug: "preventive-examination",
  },
  {
    id: "routine-checkup",
    title: "Routine Check-up",
    iconName: "Calendar",
    possibleMeaning: "Proactive screening to verify oral health, clean hard-to-reach areas, and prevent problems.",
    whyExaminationMatters: "Preventive dental visits save time, discomfort, and significant expense in the long term.",
    treatmentApproach: "Comprehensive visual and periodontal check, ultrasonic scaling, and personalized advice.",
    whenToSeekCare: "Every 6 months for adults and children.",
    suggestedTreatmentSlug: "preventive-examination",
  },
];

export const toothHotspots: Hotspot[] = [
  {
    id: "enamel",
    name: "Enamel",
    position: [0, 1.2, 0.7],
    summary: "The ultra-hard protective mineral outer shield of the tooth.",
    details: "Enamel is 96% mineralized hydroxyapatite, making it harder than bone. It shields the inner tooth from chewing forces, temperature fluctuations, and bacterial acid attacks.",
    importance: "Because enamel contains no living cells, it cannot regenerate once lost—making daily preventive care essential.",
  },
  {
    id: "dentin",
    name: "Dentin",
    position: [0, 0.4, 0.6],
    summary: "The supportive, microtubular living tissue underneath enamel.",
    details: "Dentin makes up the bulk of the tooth structure. It contains thousands of microscopic tubules transmitting thermal and physical sensations to the nerve.",
    importance: "When enamel wears away or gums recede, exposed dentin leads to sensitivity and faster-advancing decay.",
  },
  {
    id: "pulp",
    name: "Dental Pulp",
    position: [0, 0.1, 0],
    summary: "The vital core housing living nerves and blood vessels.",
    details: "The pulp chamber supplies moisture and nourishment to the tooth and communicates pain signals when irritated or infected by deep bacteria.",
    importance: "If infected, pulp tissue can be carefully cleared via root canal treatment to preserve the natural tooth.",
  },
  {
    id: "gum",
    name: "Gums (Gingiva)",
    position: [-0.8, -0.4, 0.6],
    summary: "The protective soft tissue collar sealing the tooth root.",
    details: "Healthy gums create a tight biological seal around the tooth neck, preventing bacteria from infiltrating the underlying alveolar bone.",
    importance: "Bleeding or receding gums signify inflammation (gingivitis) that requires professional attention.",
  },
  {
    id: "root",
    name: "Tooth Root & Periodontal Ligament",
    position: [0.4, -1.2, 0.4],
    summary: "The anatomical anchor securing the tooth within the jawbone.",
    details: "Tooth roots are covered in cementum and held in the bone by microscopic shock-absorbing periodontal ligament fibers.",
    importance: "Healthy roots and bone maintain bite stability and facial jaw contour.",
  },
];
